;my second scheme
(define hello 
    (lambda (name)
        (string-append "hello," name " !")
    )
)
(display (hello "friend"))
(newline)
(define x
    (lambda (x y z)
        (* x y z)
    )
)
(define a "Input three numbers")
(define b "The answer is:")
(display a)
(newline)
(define a1 (read))
(define a2 (read))
(define a3 (read))
(display b)
(newline)
(display (x a1 a2 a3))       
(newline)
