(library (main)
         (export exec)
         (import (rnrs) (repl))

         (define (exec)
           (do ((i (read) (read)))
               ((equal? i '(exit)) (exit))
               (cond
                 ((list? i) 
                  (cond
                    ((equal? (car i) '+) (apply 'i+ (cdr i)))
                    ((equal? (car i) '-) (apply 'i- (cdr i)))
                    ((equal? (car i) '*) (apply 'i* (cdr i)))
                    ((equal? (car i) '/) (apply 'i/ (cdr i)))
                    (else (display "none"))
                    )
                  )
                 (else (display "no"))
                 )
               )
           )
         )
