;If the numbers 1 to 5 are written out in words: one, two, three, four, five, then there are 3 + 3 + 5 + 4 + 4 = 19 letters used in total.
;If all the numbers from 1 to 1000 (one thousand) inclusive were written out in words, how many letters would be used?

;NOTE: Do not count spaces or hyphens. For example, 342 (three hundred and forty-two) contains 23 letters and 115 (one hundred and fifteen) contains 20 letters. The use of "and" when writing out numbers is in compliance with British usage.

(define (head n)
  (case (car (string->list (number->string n)))
    ((#\1) 1)
    ((#\2) 2)
    ((#\3) 3)
    ((#\4) 4)
    ((#\5) 5)
    ((#\6) 6)
    ((#\7) 7)
    ((#\8) 8)
    ((#\9) 9)
    ((#\0) 0)))
(define (towords n)
  (case n
    ((0) "")
    ((1) "one")
    ((2) "two")
    ((3) "three")
    ((4) "four")
    ((5) "five")
    ((6) "six")
    ((7) "seven")
    ((8) "eight")
    ((9) "nine")
    ((10) "ten")
    ((11) "eleven")
    ((12) "twelve")
    ((13) "thirteen")
    ((14) "fourteen")
    ((15) "fifteen")
    ((16) "sixteen")
    ((17) "seventeen")
    ((18) "eighteen")
    ((19) "nineteen")
    ((20) "twenty")
    ((30) "thirty")
    ((40) "forty")
    ((50) "fifty")
    ((60) "sixty")
    ((70) "seventy")
    ((80) "eighty")
    ((90) "ninety")
    ((1000) (cons "one" "thousand"))
    (else
      (cond
	((> n 100)
	 (if (= 0 (modulo n 100))
	  (list (towords (head n)) "hundred") 
	   (list (towords (head n)) "hundred" "and" (towords (modulo n 100)))))
	((= n 100) (cons "one" "hundred"))
	(else
	  (cond
	    ((> n 20) (cons (towords (* 10 (head n))) (towords (modulo n 10))))
	    ((= n 20) (towords 20))
	    ((< n 20) (towords n))))))))

(define (sumlen l)
  (cond
    ((null? l) 0)
    ((pair? l) (+ (sumlen (car l)) (sumlen (cdr l))))
    ((atom? l) (string-length l))
    (else
      (+ (sumlen (car l)) (sumlen (cdr l))))))
(define (sumall n)
  (define (sa-iter i sum)
    (if (<= i n)
      (begin
	(display (towords i))
	(display "   ")
	(display (sumlen (towords i)))
	(newline)
	(set! sum (+ sum (sumlen (towords i))))
	(sa-iter (+ i 1) sum))
      (begin
	(display "the sum is ")
	(display sum)
	(newline)
	(display "DONE"))
      ))
  (sa-iter 1 0))

(sumall 1000)
