;The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
;1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
;Let us list the factors of the first seven triangle numbers:
; 1: 1
; 3: 1,3
; 6: 1,2,3,6
;10: 1,2,5,10
;15: 1,3,5,15
;21: 1,3,7,21
;28: 1,2,4,7,14,28
;We can see that 28 is the first triangle number to have over five divisors.
;What is the value of the first triangle number to have over five hundred divisors?
;n(n+1)/2

(define (factors n)
  (display n)
  (display " : ")
    (set! sum 0)
  (define (fact-iter i)
    (if (<= i (sqrt n))
      (begin
	(if (= 0 (modulo n i))
	  (begin
	    (set! sum (+ sum 1))))
	(fact-iter (+ i 1)))
      (begin
	(display "    ")
	(display (* 2 sum))
	(if (>= (* 2 sum)  500)
	  (display "heeeeeeeeeeeeeeeeeeere!"))
	(newline))))
  (fact-iter 1))
(define (mostfact n)
  (define (mf-iter i)
    (if (<= i n)
      (begin
      (factors (/ (* i (+ i 1)) 2))
      (mf-iter (+ i 1)))))
  (mf-iter 1))


