;Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
;1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
;It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
;Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk −Pj| is minimised; what is the value of D?

(define (penta i)
  (/ (* i (- (* 3 i) 1)) 2))
(define (penta? n)
  (if (<= n 0)
    #f
    (begin
      (define dt (sqrt (+ 1 (* 24 n))))
      (define p (/ (+ 1 dt) 6))
      (if (integer? p)
	#t
	#f
	))))

(define (findpen i j d)
  (define pi (penta i))
  (define pj (penta j))
  (if (and (penta? (abs (- pi pj))) (penta? (+ pi pj)))
    (begin
      (display "pi ")
      (display pi)
      (newline)
      (display "pj ")
      (display pj)
      (newline)
      (display "|pi-pj| ")
      (display (abs (- pi pj))))
    (if (< (abs (- i j)) d)
      (findpen i (+ j 1) d)
      (begin
	(display (+ i 1))
	(newline)
	(findpen (+ i 1) (+ i 1) d)))))
(findpen 1 1 2000)
