;Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
;1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

(define (fibonacci n)
  (define (fib-iter a b count)
    (if (= count 0)
        b
	(fib-iter b (+ a b) (- count 1))))
  (fib-iter 0 1 n))
(define (fibcount n)
  (define (fc-iter i sum)
    (set! fib (fibonacci i))
    (display fib)
    (if (even? fib)
      (begin
	(display "  ok")
	(newline)
        (set! sum (+ sum fib)))
      (newline))
    (if (< fib n)
      (fc-iter (+ i 1) sum)
      (display sum)))
  (fc-iter 1 0))
(fibcount 4000000)
